version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: casecell-postgres

    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres

    volumes:
      - postgres:/data/postgres

    ports:
      - "5434:5432"

    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: casecell-redis

    ports:
      - "6379:6379"

    volumes:
      - redis:/data

    restart: unless-stopped

    command: redis-server --appendonly yes

volumes:
  postgres: 
  redis: 